### ISSUE TITLE
Not working with postgresql enums

### ISSUE THREAD

**Issue by a0s** [7even/active_record-annotate#7]
```ruby
class CreateCleanerSurchargeRates < ActiveRecord::Migration
  def up
    execute "CREATE TYPE cleaner_surcharge_value_type AS ENUM ('multiplier', 'additional')"
    create_table :cleaner_surcharge_rates do |t|
      t.column :value_type, :cleaner_surcharge_value_type, null: false, index: true
```

```ruby
# Could not dump table :cleaner_surcharge_rates because of following StandardError
#   Unknown type 'cleaner_surcharge_value_type' for column 'value_type'

class CleanerSurchargeRate < ActiveRecord::Base
```

**Comment by 7even** [comment]
It seems like the ActiveRecord schema dumper doesn't support postgres enum types (at least that's the case with ActiveRecord 4). [Here](https://stackoverflow.com/questions/7928370/custom-database-type-in-activerecord/45430348#45430348) is a possible workaround.

I'm not sure this will ever get fixed in `active_record-annotate`. Eventually [DbSchema](https://github.com/7even/db_schema) will have it's own annotation mechanism which annotates every postgres feature supported by DbSchema.
